/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AppHouseholdRouteImport } from './routes/_app/household'
import { Route as AppPlanRouteImport } from './routes/_app/plan'
import { Route as SignInSplatRouteImport } from './routes/sign-in.$'
import { Route as SignUpSplatRouteImport } from './routes/sign-up.$'
import { Route as AppJoinTokenRouteImport } from './routes/_app/join.$token'
import { Route as AppListsIndexRouteImport } from './routes/_app/lists/index'
import { Route as AppListsIdRouteImport } from './routes/_app/lists/$id'
import { Route as AppRecipesIndexRouteImport } from './routes/_app/recipes/index'
import { Route as AppRecipesNewRouteImport } from './routes/_app/recipes/new'
import { Route as AppRecipesIdIndexRouteImport } from './routes/_app/recipes/$id.index'
import { Route as AppRecipesIdEditRouteImport } from './routes/_app/recipes/$id.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AppHouseholdRoute = AppHouseholdRouteImport.update({
  id: '/household',
  path: '/household',
  getParentRoute: () => AppRoute,
} as any)
const AppPlanRoute = AppPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => AppRoute,
} as any)
const SignInSplatRoute = SignInSplatRouteImport.update({
  id: '/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpSplatRoute = SignUpSplatRouteImport.update({
  id: '/sign-up/$',
  path: '/sign-up/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppJoinTokenRoute = AppJoinTokenRouteImport.update({
  id: '/join/$token',
  path: '/join/$token',
  getParentRoute: () => AppRoute,
} as any)
const AppListsIndexRoute = AppListsIndexRouteImport.update({
  id: '/lists/',
  path: '/lists/',
  getParentRoute: () => AppRoute,
} as any)
const AppListsIdRoute = AppListsIdRouteImport.update({
  id: '/lists/$id',
  path: '/lists/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppRecipesIndexRoute = AppRecipesIndexRouteImport.update({
  id: '/recipes/',
  path: '/recipes/',
  getParentRoute: () => AppRoute,
} as any)
const AppRecipesNewRoute = AppRecipesNewRouteImport.update({
  id: '/recipes/new',
  path: '/recipes/new',
  getParentRoute: () => AppRoute,
} as any)
const AppRecipesIdIndexRoute = AppRecipesIdIndexRouteImport.update({
  id: '/recipes/$id/',
  path: '/recipes/$id/',
  getParentRoute: () => AppRoute,
} as any)
const AppRecipesIdEditRoute = AppRecipesIdEditRouteImport.update({
  id: '/recipes/$id/edit',
  path: '/recipes/$id/edit',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/household': typeof AppHouseholdRoute
  '/plan': typeof AppPlanRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/join/$token': typeof AppJoinTokenRoute
  '/lists/$id': typeof AppListsIdRoute
  '/recipes/new': typeof AppRecipesNewRoute
  '/lists/': typeof AppListsIndexRoute
  '/recipes/': typeof AppRecipesIndexRoute
  '/recipes/$id/edit': typeof AppRecipesIdEditRoute
  '/recipes/$id/': typeof AppRecipesIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/household': typeof AppHouseholdRoute
  '/plan': typeof AppPlanRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/join/$token': typeof AppJoinTokenRoute
  '/lists/$id': typeof AppListsIdRoute
  '/recipes/new': typeof AppRecipesNewRoute
  '/lists': typeof AppListsIndexRoute
  '/recipes': typeof AppRecipesIndexRoute
  '/recipes/$id/edit': typeof AppRecipesIdEditRoute
  '/recipes/$id': typeof AppRecipesIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/_app/household': typeof AppHouseholdRoute
  '/_app/plan': typeof AppPlanRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/_app/join/$token': typeof AppJoinTokenRoute
  '/_app/lists/$id': typeof AppListsIdRoute
  '/_app/recipes/new': typeof AppRecipesNewRoute
  '/_app/lists/': typeof AppListsIndexRoute
  '/_app/recipes/': typeof AppRecipesIndexRoute
  '/_app/recipes/$id/edit': typeof AppRecipesIdEditRoute
  '/_app/recipes/$id/': typeof AppRecipesIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/privacy'
    | '/terms'
    | '/household'
    | '/plan'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/join/$token'
    | '/lists/$id'
    | '/recipes/new'
    | '/lists/'
    | '/recipes/'
    | '/recipes/$id/edit'
    | '/recipes/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacy'
    | '/terms'
    | '/household'
    | '/plan'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/join/$token'
    | '/lists/$id'
    | '/recipes/new'
    | '/lists'
    | '/recipes'
    | '/recipes/$id/edit'
    | '/recipes/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/privacy'
    | '/terms'
    | '/_app/household'
    | '/_app/plan'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/_app/join/$token'
    | '/_app/lists/$id'
    | '/_app/recipes/new'
    | '/_app/lists/'
    | '/_app/recipes/'
    | '/_app/recipes/$id/edit'
    | '/_app/recipes/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  SignInSplatRoute: typeof SignInSplatRoute
  SignUpSplatRoute: typeof SignUpSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/household': {
      id: '/_app/household'
      path: '/household'
      fullPath: '/household'
      preLoaderRoute: typeof AppHouseholdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/plan': {
      id: '/_app/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof AppPlanRouteImport
      parentRoute: typeof AppRoute
    }
    '/sign-in/$': {
      id: '/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof SignInSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up/$': {
      id: '/sign-up/$'
      path: '/sign-up/$'
      fullPath: '/sign-up/$'
      preLoaderRoute: typeof SignUpSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/join/$token': {
      id: '/_app/join/$token'
      path: '/join/$token'
      fullPath: '/join/$token'
      preLoaderRoute: typeof AppJoinTokenRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/lists/': {
      id: '/_app/lists/'
      path: '/lists'
      fullPath: '/lists/'
      preLoaderRoute: typeof AppListsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/lists/$id': {
      id: '/_app/lists/$id'
      path: '/lists/$id'
      fullPath: '/lists/$id'
      preLoaderRoute: typeof AppListsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recipes/': {
      id: '/_app/recipes/'
      path: '/recipes'
      fullPath: '/recipes/'
      preLoaderRoute: typeof AppRecipesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recipes/new': {
      id: '/_app/recipes/new'
      path: '/recipes/new'
      fullPath: '/recipes/new'
      preLoaderRoute: typeof AppRecipesNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recipes/$id/': {
      id: '/_app/recipes/$id/'
      path: '/recipes/$id'
      fullPath: '/recipes/$id/'
      preLoaderRoute: typeof AppRecipesIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recipes/$id/edit': {
      id: '/_app/recipes/$id/edit'
      path: '/recipes/$id/edit'
      fullPath: '/recipes/$id/edit'
      preLoaderRoute: typeof AppRecipesIdEditRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppHouseholdRoute: typeof AppHouseholdRoute
  AppPlanRoute: typeof AppPlanRoute
  AppJoinTokenRoute: typeof AppJoinTokenRoute
  AppListsIdRoute: typeof AppListsIdRoute
  AppRecipesNewRoute: typeof AppRecipesNewRoute
  AppListsIndexRoute: typeof AppListsIndexRoute
  AppRecipesIndexRoute: typeof AppRecipesIndexRoute
  AppRecipesIdEditRoute: typeof AppRecipesIdEditRoute
  AppRecipesIdIndexRoute: typeof AppRecipesIdIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppHouseholdRoute: AppHouseholdRoute,
  AppPlanRoute: AppPlanRoute,
  AppJoinTokenRoute: AppJoinTokenRoute,
  AppListsIdRoute: AppListsIdRoute,
  AppRecipesNewRoute: AppRecipesNewRoute,
  AppListsIndexRoute: AppListsIndexRoute,
  AppRecipesIndexRoute: AppRecipesIndexRoute,
  AppRecipesIdEditRoute: AppRecipesIdEditRoute,
  AppRecipesIdIndexRoute: AppRecipesIdIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  SignInSplatRoute: SignInSplatRoute,
  SignUpSplatRoute: SignUpSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
